### PR TITLE
+ Method: PcapHandle.sendPacket(final byte[] bytes, final int len)

### PR DESCRIPTION
**Pull request by betschwa**

### CODE REVIEW

**Comment by kaitoy** [comment]
Is this new method really needed or useful?
What is the usecase?

**Comment by betschwa** [comment]
Yes, it is.
I need to send large amount of packages (currently > 500.000/s) and with this method I don't need to create a new byte array for each package. I can re-use the old one.

**Comment by kaitoy** [comment]
Thank you for your contribution.
I merged it.

**Comment by betschwa** [comment]
Thank you.

**Pull request merged**
