### PR TITLE
Issue #61

### PR DESCRIPTION
**Pull request by zahidMed**
Add setDirection for sniffing incoming, outgoing or both traffics

### CODE REVIEW

**Comment by kaitoy** [comment]
Your implementation shouldn't work.
Please test it before sending PR.

**Comment by zahidMed** [comment]
why, I tested it on linux SLES 11 SP2, it work fine.

**Comment by zahidMed** [comment]
This faillure is related to the class org.pcap4j.util.ByteArraysTest. I didn't modify it.

**Comment by kaitoy** [comment]
There are obviously 2 errors at least.
The name of the function added to NativeMappings is wrong.
The native method setDirection() calls is wrong.

**Comment by kaitoy** [comment]
BTW, It seems that the build failure in Travis CI is due to [a bug in Travis CI side](https://github.com/travis-ci/travis-ci/issues/5669).

**Comment by kaitoy** [comment]
I made it by myself.

**Pull request closed without merging**
