### PR TITLE
Cursor movement in parsing UDP rData parsing

### PR DESCRIPTION
**Pull request by WhiteFangBuck**
Ref: https://github.com/kaitoy/pcap4j/issues/98#issuecomment-302257105

### CODE REVIEW

**Comment by kaitoy** [comment]
The fix for `DnsPacket.java` is wrong. With this fix, Pcap4J can't build the original raw data from a DnsPacket object.
The fix for pom.xml is not related to the issue and must be removed.

**Comment by WhiteFangBuck** [comment]
"...The fix for DnsPacket.java is wrong. With this fix, Pcap4J can't build the original raw data from a DnsPacket object..."

What would you recommend here? I do not have experience with parsing DNS payloads. This change seemed to resolve the length exceptions.

**Comment by kaitoy** [comment]
I'm making the fix.
With the fix, Pcap4J will dissect the A record in #98 as it resolves `olimp.us` to `137.126.8.240` instead of `49.51.55.46` .

**Comment by kaitoy** [comment]
I made the fix. (5e5ed5db)

**Comment by WhiteFangBuck** [comment]
Thank you! I apologize for delayed response. I am traveling for work this week and have not been able to test on my data yet.

Cheers
Vartika

**Pull request closed without merging**
