### PR TITLE
#207: Fix automatic module name and split package issue

### PR DESCRIPTION
**Pull request by Jojor**
Gitlab issue: #207
Since Java 9 modularity, if JARs used in a modular environment doesn't
provide a module name, the JAR name will be used by default. The module
packetfactory-static caused an issue because of the static keyword so I
told maven to add the automatic module name in the manifest without the
static keywork.
Also, classes in separate modules must not have the same package path,
this is commonly called the split-package issue. There was a conflict
between the packetfactory-static and pcap4j-core because they both
declared classes in ord/pcap4j/factory. I changed the
packetfactory-static packages to avoid the splitpackage issue.

### CODE REVIEW

**Comment by Jojor** [comment]
Sorry for the mistakes in my commit message, I think I need to get some sleep :)
I'm a bit confused about why the CI is failing as my modifications should not impact the app behavior but I just wanted to do a PR to show you how I patched it in my local repo to make it work. If you have a better idea in mind I can help implementing it

**Comment by Jojor** [comment]
Ok I understand why everything is failing. I changed the package name to fix the split package issue between the pcap4j-core and the pcap4j-packetfactory-static but it was used on purpose to provide the PacketFactoryBinder to the PacketFactories. So currently all the packets are built as UnknownPacket by the SimplePacketFactoryBinder.
I tried something different with [ServiceLoaders](https://docs.oracle.com/javase/9/docs/api/java/util/ServiceLoader.html) and it seems to be working well. I'll push my changes again and propagate that to the other modules.

**Comment by kaitoy** [comment]
Thank you for your PR. I will take a look at it.

**Comment by Jojor** [comment]
Travis is failing with the JDK7 but not the 8 because I'm using Optional that exists only since JDK8. Is it a need to run the project on JDK 7 or can we move forward to JDK8 ?
If so, we should remember to upgrade the version of the maven compiler plugin in the pom.xml that is still to 1.7.

**Comment by matthieugrieger** [comment]
What's the status of this? I began implementing a Java 12 project and this issue is preventing me from using this library.

**Comment by Jojor** [comment]
Waiting for @kaitoy code review.
I'm using my patch in production for 2 months now and it works well. You could build your own snapshot as I did so you will be able to move forward while waiting for a release with that fix.

**Comment by matthieugrieger** [comment]
@Jojor: Thanks, will give it a shot.

**Comment by kaitoy** [comment]
I merged this PR manually because I wanted to remove some unrelated changes such as ones on CI configs and Java compiler's source/target versions.

**Pull request closed without merging**
